brews:
  - name: goal

    # GitHub/GitLab repository to push the formula to
    tap:
      owner: aaabramov
      name: goal
      branch: master

    url_template: "https://github.com/aaabramov/goal/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com

    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    folder: Formula

    # Caveats for the user of your binary.
    caveats: "See https://github.com/aaabramov/goal"

    # Your app's homepage.
    homepage: "https://github.com/aaabramov/goal"

    # Template of your app's description.
    description: "Use your aliases safely"

    # SPDX identifier of your app's license.
    license: "Apache-2.0"

    # So you can `brew test` your formula.
    # Default is empty.
    # TODO?
    #    test: |
    #      system "#{bin}/program --version"
    #      ...

    # Custom install script for brew.
    # Default is 'bin.install "program"'.
    #    install: |
    #      bin.install "program"
    #      ...

    # Custom post_install script for brew.
    # Could be used to do any additional work after the "install" script
    # Default is empty.
#    post_install: |
#      etc.install "app-config.conf"
#      ...
