# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goal < Formula
  desc "Allows you to create local aliases withing directory/repository with proper assertions upon executions."
  homepage "https://github.com/aaabramov/goal"
  version "0.0.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaabramov/goal/releases/download/0.0.9/goal_0.0.9_darwin_amd64.tar.gz"
      sha256 "c6a9f9e9f8488b4c4e041bfb4ca30839067d8749c38f326cc6a7ee483310859c"

      def install
        bin.install "goal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaabramov/goal/releases/download/0.0.9/goal_0.0.9_darwin_arm64.tar.gz"
      sha256 "caf1b10a15eb5239dc3d91412e42aa9afc342de76021b4648e82cc5abf05007b"

      def install
        bin.install "goal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaabramov/goal/releases/download/0.0.9/goal_0.0.9_linux_arm64.tar.gz"
      sha256 "43ee6158d3f26c155462e7e60b9ed44ea627b233d573a1c7676004f38e9203a2"

      def install
        bin.install "goal"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/aaabramov/goal/releases/download/0.0.9/goal_0.0.9_linux_amd64.tar.gz"
      sha256 "a7bcaac2d86166b4bb2f0042e67792d5ca69f794c420c7e2d0a9fbf946f9a78e"

      def install
        bin.install "goal"
      end
    end
  end

  def caveats; <<~EOS
    See https://github.com/aaabramov/goal
  EOS
  end
end
