# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goal < Formula
  desc "Allows you to create local aliases withing directory/repository with proper assertions upon executions."
  homepage "https://github.com/aaabramov/goal"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aaabramov/goal/releases/download/0.0.8/goal_0.0.8_darwin_amd64.tar.gz"
      sha256 "060bb1ca5f3eef06fd96853826e32afb370986e17a917bad4d0fa213c2fff8ee"

      def install
        bin.install "goal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aaabramov/goal/releases/download/0.0.8/goal_0.0.8_darwin_arm64.tar.gz"
      sha256 "4158df7caa4d39161bc9d57b703eaf635523a1bdbbe34570877b4437b9370d38"

      def install
        bin.install "goal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/aaabramov/goal/releases/download/0.0.8/goal_0.0.8_linux_amd64.tar.gz"
      sha256 "0f819c0369e4030ed66a08e6fd850017c03735c8e4056f793514f1f4e3418e9d"

      def install
        bin.install "goal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aaabramov/goal/releases/download/0.0.8/goal_0.0.8_linux_arm64.tar.gz"
      sha256 "332802d4c4088f36c7d67a808cf122f2e532507dcf409c7ffb18730f9956766f"

      def install
        bin.install "goal"
      end
    end
  end

  def caveats; <<~EOS
    See https://github.com/aaabramov/goal
  EOS
  end
end
